# Dependabot configuration for automated dependency updates
# This ensures security patches and updates are automatically proposed
# Aligns with PhD research roadmap: Supply Chain Security (Phase 1)

version: 2
updates:
  # Root Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "GOATnote-Inc/research-team"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
    groups:
      # Group minor/patch updates together
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"

  # App directory Python dependencies
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "GOATnote-Inc/research-team"
    labels:
      - "dependencies"
      - "app"
      - "security"
    commit-message:
      prefix: "deps(app)"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "GOATnote-Inc/research-team"
    labels:
      - "dependencies"
      - "ci/cd"
    commit-message:
      prefix: "ci"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "GOATnote-Inc/research-team"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
