weights:
  exec_sponsor: 0.2
  data_access: 0.2
  workflow_speed: 0.2
  potential_value: 0.2
  risk: 0.1
  champion: 0.1
candidates:
  - name: Lab A
    exec_sponsor: 5
    data_access: 4
    workflow_speed: 5
    potential_value: 5
    risk: 2
    champion: 5
    notes: "Fast moving assay team with strong sponsor"
  - name: Lab B
    exec_sponsor: 3
    data_access: 5
    workflow_speed: 3
    potential_value: 4
    risk: 1
    champion: 2
    notes: "Data rich but slower process"
  - name: Ops Team C
    exec_sponsor: 4
    data_access: 3
    workflow_speed: 4
    potential_value: 3
    risk: 4
    champion: 4
    notes: "Higher compliance risk"
