# robust-kbench Configuration for L4 FlashAttention Optimization
# Phase 3: Micro-benchmarking integration

# Benchmark parameters
warmups: 20
iterations: 100

# Output settings
output_dir: "benchmarks/l4/rbk_results"
save_json: true
save_csv: true
save_markdown: true

# Shape grid: Canonical configurations for optimization
shapes:
  # Canonical 1: Large batch, long sequence (primary optimization target)
  - name: "canonical_1_large_batch"
    batch_size: 4
    num_heads: 16
    seq_len: 2048
    head_dim: 128
    causal: true
    dtype: "float16"
  
  # Canonical 2: Single batch, very long sequence (memory stress)
  - name: "canonical_2_long_seq"
    batch_size: 1
    num_heads: 8
    seq_len: 4096
    head_dim: 128
    causal: true
    dtype: "float16"
  
  # Canonical 3: Moderate batch, moderate sequence (balanced)
  - name: "canonical_3_balanced"
    batch_size: 8
    num_heads: 16
    seq_len: 1024
    head_dim: 64
    causal: false
    dtype: "float16"
  
  # Standard shapes for comprehensive testing
  - name: "std_small_fp16"
    batch_size: 1
    num_heads: 8
    seq_len: 512
    head_dim: 64
    causal: false
    dtype: "float16"
  
  - name: "std_medium_fp16"
    batch_size: 4
    num_heads: 8
    seq_len: 1024
    head_dim: 64
    causal: true
    dtype: "float16"
  
  - name: "std_large_fp16"
    batch_size: 4
    num_heads: 16
    seq_len: 2048
    head_dim: 128
    causal: true
    dtype: "float16"
  
  # BF16 variants
  - name: "std_medium_bf16"
    batch_size: 4
    num_heads: 8
    seq_len: 1024
    head_dim: 64
    causal: true
    dtype: "bfloat16"
  
  - name: "std_large_bf16"
    batch_size: 4
    num_heads: 16
    seq_len: 2048
    head_dim: 128
    causal: true
    dtype: "bfloat16"
  
  # Head dimension variants
  - name: "head_dim_80"
    batch_size: 4
    num_heads: 8
    seq_len: 1024
    head_dim: 80
    causal: true
    dtype: "float16"
  
  - name: "head_dim_96"
    batch_size: 4
    num_heads: 8
    seq_len: 1024
    head_dim: 96
    causal: true
    dtype: "float16"
  
  # Stress tests (optional, comment out if too slow)
  # - name: "stress_8k_seq"
  #   batch_size: 1
  #   num_heads: 8
  #   seq_len: 8192
  #   head_dim: 128
  #   causal: true
  #   dtype: "float16"

