# Phase 2 hardware integration campaign configuration
campaign:
  name: "phase2-uvvis-integration"
  target_experiments: 50
  duration_hours: 24
  instrument: "uvvis-001"
  dataset: "configs/uv_vis_reference_library.json"
  facility:
    name: "Stanford Nano Shared Facilities"
    contact: "ops@snf.stanford.edu"
    agreement_status: "pending-final-signature"
  safety:
    emergency_contact: "lab-safety@periodic.ai"
    interlocks:
      - "cuvette_inserted"
      - "lid_closed"
      - "lamp_warm"
      - "power_monitoring"
    escalation:
      - role: "Lab Manager"
        contact: "lab.manager@periodic.ai"
      - role: "Safety Officer"
        contact: "safety.officer@periodic.ai"
  storage:
    primary: "gcs://periodicdent42-phase2-data"
    fallback: "data/local_storage"
  reporting:
    daily_summary: true
    ingest_to_cloud_sql: true
