version: "3.9"
services:
  orchestrator:
    build:
      context: .
      dockerfile: docker/orchestrator.Dockerfile
    env_file:
      - .env.example
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8080
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PASS=changeme
    ports:
      - "3000:3000"
    depends_on:
      - orchestrator
