# Cloud Build configuration for HTC-enabled backend
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ard-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ard-backend:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ard-backend:$COMMIT_SHA'
    id: 'push-sha'
    
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ard-backend:latest'
    id: 'push-latest'
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ard-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ard-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID,GCP_REGION=us-central1,LOG_LEVEL=INFO'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:ard-intelligence-db'
      - '--service-account'
      - 'ard-backend@$PROJECT_ID.iam.gserviceaccount.com'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    id: 'deploy'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ard-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ard-backend:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
timeout: '1200s'  # 20 minutes

