defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

seed: 42
model_name: simple-glassbox
max_seq_len: 512
data_path: data/processed
lr: 0.01
epochs: 10
eval_every: 1
patience: 3
checkpoint_dir: training/model_registry
