# Active Learning with UCB Acquisition and Diversity Selection

seed: 42
deterministic: true

paths:
  data_root: data
  processed_data: data/processed
  models: models
  evidence: evidence

data:
  test_size: 0.20
  val_size: 0.10
  seed_labeled_size: 50
  stratify_bins: 5
  near_dup_threshold: 0.995

features:
  use_matminer: true
  featurizer_type: magpie
  n_components_pca: null
  scale_method: standard

# Base model for AL
model:
  model_type: rf_qrf
  n_estimators: 200
  max_depth: 30
  min_samples_split: 5
  min_samples_leaf: 2
  max_features: sqrt
  bootstrap: true
  quantiles: [0.025, 0.975]
  random_state: 42
  n_jobs: -1

# Active learning configuration
active_learning:
  acquisition_fn: ucb  # ucb, ei, max_var, eig_proxy
  diversity_method: kmedoids  # kmedoids, dpp, null
  diversity_weight: 0.3
  budget_total: 200  # Total queries allowed
  k_per_round: 10  # Candidates per round
  ucb_beta: 2.0  # Exploration weight
  cost_weight: 0.0  # No cost penalty (set >0 if cost model available)
  risk_gate_sigma_max: 10.0  # Max uncertainty (in Tc units)
  ood_block: true  # Block OOD candidates

uncertainty:
  conformal_method: mondrian
  conformal_alpha: 0.05
  ece_n_bins: 15
  calibration_size: 0.3

ood:
  mahalanobis_quantile: 0.95
  kde_bandwidth: null
  kde_quantile: 0.05
  conformal_risk_threshold: 0.90

log_level: INFO

# AL-specific settings
al_settings:
  n_rounds: 20  # 20 rounds × 10 per round = 200 total
  top_m_candidates: 50  # Score top-50, then diversity-select top-10
  save_intermediate: true  # Save model after each round
  plot_frequency: 5  # Generate plots every 5 rounds
  random_baseline: true  # Run random baseline for comparison
  n_seeds: 5  # Run with 5 different random seeds

