# Random Forest with Quantile Regression Forest Configuration

seed: 42
deterministic: true

paths:
  data_root: data
  processed_data: data/processed
  models: models
  evidence: evidence

data:
  test_size: 0.20
  val_size: 0.10
  seed_labeled_size: 50
  stratify_bins: 5
  near_dup_threshold: 0.995

features:
  use_matminer: true
  featurizer_type: magpie
  n_components_pca: null  # No PCA
  scale_method: standard

model:
  model_type: rf_qrf
  n_estimators: 200
  max_depth: 30
  min_samples_split: 5
  min_samples_leaf: 2
  max_features: sqrt
  bootstrap: true
  quantiles: [0.025, 0.975]  # 95% PI
  random_state: 42
  n_jobs: -1

uncertainty:
  conformal_method: mondrian  # Per-family calibration
  conformal_alpha: 0.05  # 95% coverage
  ece_n_bins: 15
  calibration_size: 0.3  # 30% of train for calibration

ood:
  mahalanobis_quantile: 0.95
  kde_bandwidth: null  # Auto
  kde_quantile: 0.05
  conformal_risk_threshold: 0.90

log_level: INFO

