workflow_name: "Assay Validation"
steps:
  - name: "queue"
    description: "Awaiting assignment"
  - name: "work"
    description: "Technician executing protocol"
  - name: "review"
    description: "QA review"
  - name: "done"
    description: "Completed and logged"
value_stream:
  - step: "queue"
    entry_state: "entered"
    exit_state: "exited"
  - step: "work"
    entry_state: "entered"
    exit_state: "exited"
  - step: "review"
    entry_state: "entered"
    exit_state: "exited"
  - step: "done"
    entry_state: "entered"
    exit_state: "exited"
