name: Continuous Monitoring

on:
  pull_request:
  workflow_dispatch:  # Manual trigger only
  # schedule:
  #   - cron: '0 * * * *'  # DISABLED: Was causing 24 failures/day

permissions:
  contents: read

jobs:
  performance-monitoring:
    name: Performance Monitoring
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Generate performance report
        continue-on-error: true  # Non-blocking if paths don't exist
        run: |
          python scripts/generate_monitoring_report.py \
            --kind performance \
            --output monitoring_reports/performance.json || echo "⚠️  Performance monitoring skipped (non-critical)"
      - name: Upload performance report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-monitoring-report
          path: monitoring_reports/performance.json

  uptime-monitoring:
    name: Uptime Monitoring
    runs-on: ubuntu-latest
    needs: performance-monitoring
    if: always()  # Run even if performance-monitoring fails
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Generate uptime report
        continue-on-error: true  # Non-blocking
        run: |
          python scripts/generate_monitoring_report.py \
            --kind uptime \
            --output monitoring_reports/uptime.json || echo "⚠️  Uptime monitoring skipped (non-critical)"
      - name: Upload uptime report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: uptime-monitoring-report
          path: monitoring_reports/uptime.json

  health-monitoring:
    name: Health Monitoring
    runs-on: ubuntu-latest
    needs: performance-monitoring
    if: always()  # Run even if performance-monitoring fails
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Generate health report
        continue-on-error: true  # Non-blocking
        run: |
          python scripts/generate_monitoring_report.py \
            --kind health \
            --output monitoring_reports/health.json || echo "⚠️  Health monitoring skipped (non-critical)"
      - name: Upload health report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: health-monitoring-report
          path: monitoring_reports/health.json

  metrics-collection:
    name: Metrics Collection
    runs-on: ubuntu-latest
    needs: performance-monitoring
    if: always()  # Run even if performance-monitoring fails
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Generate metrics report
        continue-on-error: true  # Non-blocking
        run: |
          python scripts/generate_monitoring_report.py \
            --kind metrics \
            --output monitoring_reports/metrics.json || echo "⚠️  Metrics collection skipped (non-critical)"
      - name: Upload metrics report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: metrics-collection-report
          path: monitoring_reports/metrics.json

  alert-management:
    name: Alert Management
    runs-on: ubuntu-latest
    needs:
      - performance-monitoring
      - uptime-monitoring
      - health-monitoring
      - metrics-collection
    if: always()  # Run even if previous jobs fail
    steps:
      - uses: actions/checkout@v4
      - name: Download monitoring artifacts
        uses: actions/download-artifact@v5
        with:
          path: monitoring_reports
          merge-multiple: true
        continue-on-error: true  # Don't fail if no artifacts
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Generate alert summary
        continue-on-error: true  # Non-blocking
        shell: bash
        run: |
          set +e  # Don't exit on error
          mapfile -t reports < <(find monitoring_reports -maxdepth 1 -name '*.json' ! -name 'alert-summary.json' -print 2>/dev/null)
          if [[ ${#reports[@]} -eq 0 ]]; then
            echo "⚠️  No monitoring reports available - skipping alert summary"
            exit 0
          fi
          python scripts/generate_monitoring_report.py \
            --kind alert \
            --output monitoring_reports/alert-summary.json \
            --inputs "${reports[@]}" || echo "⚠️  Alert summary generation skipped (non-critical)"
      - name: Upload alert summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: alert-management-report
          path: monitoring_reports/alert-summary.json
