name: CUDA Benchmark

on:
  pull_request:
    paths:
      - 'cudadent42/**/*.cu'
      - 'cudadent42/**/*.cpp'
      - 'cudadent42/bench/**'
      - 'cudadent42/setup.py'
  workflow_dispatch:

env:
  BASELINE_FILE: cudadent42/bench/.baseline.json
  REGRESSION_THRESHOLD: -3.0

jobs:
  benchmark:
    name: Benchmark
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'benchmark') || github.event_name == 'workflow_dispatch'
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check CUDA
      run: |
        export PATH="/usr/local/cuda-12.8/bin:$PATH"
        export LD_LIBRARY_PATH="/usr/local/cuda-12.8/lib64:$LD_LIBRARY_PATH"
        nvidia-smi
        nvcc --version
    
    - name: Install dependencies
      run: |
        pip install torch numpy
    
    - name: Build
      run: |
        export PATH="/usr/local/cuda-12.8/bin:$PATH"
        export LD_LIBRARY_PATH="/usr/local/cuda-12.8/lib64:$LD_LIBRARY_PATH"
        cd cudadent42
        python setup.py build_ext --inplace
    
    - name: Benchmark
      id: bench
      run: |
        export LD_LIBRARY_PATH="/usr/local/cuda-12.8/lib64:$LD_LIBRARY_PATH"
        cd cudadent42/bench
        python integrated_test.py --output results.json
      continue-on-error: true
    
    - name: Check baseline
      id: baseline
      run: |
        if [ -f "${{ env.BASELINE_FILE }}" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Compare
      id: compare
      if: steps.baseline.outputs.exists == 'true'
      run: |
        cd cudadent42/bench
        python compare_baseline.py results.json \
          --baseline ../../${{ env.BASELINE_FILE }} \
          --threshold ${{ env.REGRESSION_THRESHOLD }} \
          --output comparison.json
      continue-on-error: true
    
    - name: Update baseline on main
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cp cudadent42/bench/results.json ${{ env.BASELINE_FILE }}
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ${{ env.BASELINE_FILE }}
        git commit -m "Update baseline [skip ci]"
        git push
    
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: |
          cudadent42/bench/results.json
          cudadent42/bench/comparison.json
        retention-days: 30

